spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  servlet:
    context-path: /api

jwt:
  secret: test-secret-key-123
  expiration: 3600000 # 1 hour in milliseconds

stripe:
  secret:
    key: sk_test_1234567890
  webhook:
    secret: whsec_test_1234567890

alpha-vantage:
  api:
    key: test_api_key_123

logging:
  level:
    root: INFO
    com.foreigntrading: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate: INFO 